// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtlgwmuvztfccsfwbypa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10bGd3bXV2enRmY2NzZndieXBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMTE4MzYsImV4cCI6MjA2MTg4NzgzNn0.d_6wBofex5vBM7wpRhn6hTj2VdNYC4Vd8bCAXyg0sKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);